// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Walk-through body & feedback storage.
//!
//! A *walk-through* is a sequenced tour authored by an LLM:
//! ordered steps with narration, each pointing at one of the existing
//! viewers (class / file / markdown / diff / note). The LLM drives via
//! the MCP tools `walkthrough_start / append / set_step / clear`; the
//! GUI displays the current step and lets the user acknowledge or ask
//! for more detail. Those user actions get appended to a separate
//! feedback file, which the LLM polls to know what the user wants.
//!
//! The body and feedback live next to the statefile:
//!
//! ```text
//! $cache/plaintext-ide/
//!   current.json            # existing — UiState; pointer is in here
//!   ui-heartbeat.json       # existing
//!   walkthrough.json        # ← body (this module)
//!   walkthrough-feedback.json   # ← user → LLM channel (this module)
//! ```
//!
//! Splitting body from `current.json` keeps the high-traffic statefile
//! tiny: every `walkthrough_set_step` is a `seq` bump on `current.json`,
//! never a re-write of the (potentially large) narration.

use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

/// One stop in the tour. The `target` field decides which viewer
/// renders the step; the rest is metadata + the LLM's narration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WalkthroughStep {
    /// Short, human-readable step title (sidebar entry).
    pub title: String,
    /// Optional markdown narration shown alongside the target.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub narration: String,
    /// What to render in the main pane.
    pub target: WalkthroughTarget,
}

/// What kind of thing the step is pointing at. Each variant maps 1:1
/// to a viewer the GUI already has, plus a `note` mode that's narration-
/// only (useful for "let me explain the context first" steps).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum WalkthroughTarget {
    /// A class in the open repository.
    Class {
        /// Fully-qualified class name.
        fqn: String,
        /// Line ranges to highlight (1-based, inclusive).
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        highlight: Vec<LineRange>,
    },
    /// An arbitrary file (markdown is rendered, others as plain source).
    File {
        /// Absolute path on disk.
        path: PathBuf,
        /// Heading slug (markdown only).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        anchor: Option<String>,
        /// Line ranges to highlight (non-markdown only; markdown ignores it).
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        highlight: Vec<LineRange>,
    },
    /// A unified diff between two refs (or `ref` vs working tree).
    Diff {
        /// Base ref (e.g. `HEAD~5`, branch name).
        reference: String,
        /// Optional target ref. `None` means working tree.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        to: Option<String>,
    },
    /// Pure narration; nothing rendered in the target pane.
    Note,
}

/// 1-based inclusive line range.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct LineRange {
    /// First line of the range (1-based, inclusive).
    pub from: u32,
    /// Last line of the range (1-based, inclusive).
    pub to: u32,
}

/// Full walk-through body. The current step pointer lives in
/// [`crate::state::UiState`] / [`crate::state::ViewIntent::Walkthrough`],
/// not here — bumping the pointer must not require rewriting the
/// (potentially large) body.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Walkthrough {
    /// Stable handle. Generated by `walkthrough_start` if not provided.
    pub id: String,
    /// Tour title (header + sidebar caption).
    pub title: String,
    /// Optional one-paragraph intro shown above step 1.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub summary: String,
    /// Ordered steps. Length ≥ 1 once the tour has started.
    pub steps: Vec<WalkthroughStep>,
    /// Unix-seconds timestamp of last write — coarse `mtime` so the GUI
    /// can detect stale tours without consulting the FS.
    #[serde(default)]
    pub updated_at: u64,
}

/// One feedback event from the user, tied to a step. Append-only.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct FeedbackEvent {
    /// Walk-through id this belongs to.
    pub walkthrough_id: String,
    /// 0-based step index when the event happened.
    pub step: u32,
    /// What the user did.
    pub kind: FeedbackKind,
    /// Optional free-text note (only for `more_detail` today).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// Unix-seconds timestamp.
    pub ts: u64,
}

/// Categorical user action.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum FeedbackKind {
    /// "I read & understood this step." Advances the pointer.
    Understood,
    /// "Please explain this in more detail." Pointer stays put; the
    /// LLM is expected to amend the step's narration (or insert a new
    /// step before continuing).
    MoreDetail,
}

/// Feedback log — the whole file, replayed each time. Tiny; it's a few
/// kilobytes per tour at most.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FeedbackLog {
    /// All events in arrival order.
    pub events: Vec<FeedbackEvent>,
}

// ----- Paths ---------------------------------------------------------------

/// Path of the body file. Always next to the statefile.
#[must_use]
pub fn body_path() -> PathBuf {
    sibling("walkthrough.json")
}

/// Path of the feedback log.
#[must_use]
pub fn feedback_path() -> PathBuf {
    sibling("walkthrough-feedback.json")
}

fn sibling(name: &str) -> PathBuf {
    let state = crate::state::statefile_path();
    let parent = state
        .parent()
        .map_or_else(std::env::temp_dir, Path::to_path_buf);
    parent.join(name)
}

// ----- IO ------------------------------------------------------------------

/// Read the current walk-through body, or `None` if no tour is active.
pub fn read_body() -> std::io::Result<Option<Walkthrough>> {
    read_at::<Walkthrough>(&body_path())
}

/// Read the feedback log. Returns an empty log if the file is missing.
pub fn read_feedback() -> std::io::Result<FeedbackLog> {
    Ok(read_at::<FeedbackLog>(&feedback_path())?.unwrap_or_default())
}

/// Write the body atomically. Stamps `updated_at` automatically.
pub fn write_body(mut body: Walkthrough) -> std::io::Result<Walkthrough> {
    body.updated_at = now_secs();
    write_atomic(&body_path(), &body)?;
    Ok(body)
}

/// Append one event to the feedback log atomically.
pub fn append_feedback(event: FeedbackEvent) -> std::io::Result<FeedbackLog> {
    let mut log = read_feedback()?;
    log.events.push(event);
    write_atomic(&feedback_path(), &log)?;
    Ok(log)
}

/// Remove body & feedback. No-op if either is already absent.
pub fn clear() -> std::io::Result<()> {
    let body = body_path();
    let fb = feedback_path();
    for p in [body, fb] {
        match std::fs::remove_file(&p) {
            Ok(()) => {}
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => return Err(e),
        }
    }
    Ok(())
}

fn read_at<T: serde::de::DeserializeOwned>(path: &Path) -> std::io::Result<Option<T>> {
    match std::fs::read_to_string(path) {
        Ok(s) => serde_json::from_str(&s)
            .map(Some)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e)),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(e),
    }
}

fn write_atomic<T: Serialize>(path: &Path, value: &T) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let json = serde_json::to_string_pretty(value)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
    let tmp = path.with_extension("json.tmp");
    std::fs::write(&tmp, json)?;
    std::fs::rename(&tmp, path)
}

fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

// ----- ID generation -------------------------------------------------------

/// Make a slug-friendly id from a tour title. Falls back to a timestamp-
/// based handle if the title slug would be empty.
#[must_use]
pub fn slugify_id(title: &str) -> String {
    let slug: String = title
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect::<String>()
        .split('-')
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("-");
    if slug.is_empty() {
        format!("wt-{}", now_secs())
    } else {
        format!("{}-{}", &slug[..slug.len().min(40)], now_secs())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_lock;

    fn override_state(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "plaintext-ide-wt-{name}-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let p = dir.join("current.json");
        std::env::set_var("PLAINTEXT_IDE_STATE", &p);
        p
    }

    #[test]
    fn body_round_trip() {
        let _g = test_lock();
        let _ = override_state("body");
        let _ = clear();
        let body = Walkthrough {
            id: "demo".into(),
            title: "Demo tour".into(),
            summary: "What changed".into(),
            steps: vec![WalkthroughStep {
                title: "First".into(),
                narration: "hello".into(),
                target: WalkthroughTarget::Note,
            }],
            updated_at: 0,
        };
        let written = write_body(body).unwrap();
        assert!(written.updated_at > 0);
        let read = read_body().unwrap().expect("body present");
        assert_eq!(read.id, "demo");
        assert_eq!(read.steps.len(), 1);
    }

    #[test]
    fn feedback_log_appends() {
        let _g = test_lock();
        let _ = override_state("fb");
        let _ = clear();
        let log = read_feedback().unwrap();
        assert!(log.events.is_empty());

        let ev1 = FeedbackEvent {
            walkthrough_id: "t".into(),
            step: 0,
            kind: FeedbackKind::Understood,
            comment: None,
            ts: 1,
        };
        let log = append_feedback(ev1).unwrap();
        assert_eq!(log.events.len(), 1);

        let ev2 = FeedbackEvent {
            walkthrough_id: "t".into(),
            step: 1,
            kind: FeedbackKind::MoreDetail,
            comment: Some("zoom in on the highlight".into()),
            ts: 2,
        };
        let log = append_feedback(ev2).unwrap();
        assert_eq!(log.events.len(), 2);
        assert_eq!(log.events[1].kind, FeedbackKind::MoreDetail);
    }

    #[test]
    fn clear_removes_both_files() {
        let _g = test_lock();
        let _ = override_state("clr");
        let _ = clear();
        write_body(Walkthrough {
            id: "x".into(),
            title: "x".into(),
            summary: "".into(),
            steps: vec![],
            updated_at: 0,
        })
        .unwrap();
        append_feedback(FeedbackEvent {
            walkthrough_id: "x".into(),
            step: 0,
            kind: FeedbackKind::Understood,
            comment: None,
            ts: 0,
        })
        .unwrap();
        clear().unwrap();
        assert!(read_body().unwrap().is_none());
        assert!(read_feedback().unwrap().events.is_empty());
    }

    #[test]
    fn slugify_id_handles_punctuation() {
        let id = slugify_id("Markdown Viewer: rollout — phase 1");
        assert!(id.starts_with("markdown-viewer-rollout-phase-1-"));
    }

    #[test]
    fn slugify_id_falls_back_when_empty() {
        let id = slugify_id("!!! ??? ###");
        assert!(id.starts_with("wt-"));
    }
}
